[tool.ariadne-codegen]
queries_path = "queries.graphql"
schema_path = "schema.graphql"
target_package_name = "galley_client"
client_name = "GalleyClient"
async_client = false
include_all_inputs = false
include_all_enums = false
convert_to_snake_case = false
