[tool.ariadne-codegen]
queries_path = "queries.graphql"
schema_path = "schema.graphql"
target_package_name = "client"
target_package_path = "galley"
client_name = "Client"
async_client = false
include_all_inputs = false
include_all_enums = false
convert_to_snake_case = false
