# Generated by ariadne-codegen
# Source: schema.graphql

from enum import Enum


class CategoryItemTypeEnum(str, Enum):
    menuItem = "menuItem"
    ingredient = "ingredient"
    recipe = "recipe"
    menu = "menu"
    vendorItem = "vendorItem"
    purchaseOrder = "purchaseOrder"
    order = "order"
    collection = "collection"
