# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CategoryItemTypeEnum


class CategoryFields(BaseModel):
    id: str
    name: str
    category: "CategoryFieldsCategory"


class CategoryFieldsCategory(BaseModel):
    id: str
    name: str
    itemType: CategoryItemTypeEnum


class NutritionFields(BaseModel):
    addedSugarG: Optional[float]
    addedSugarPercentDRV: Optional[float]
    calciumMg: Optional[float]
    calciumPercentRDI: Optional[float]
    caloriesKCal: Optional[float]
    carbsG: Optional[float]
    carbsPercentDRV: Optional[float]
    cholesterolMg: Optional[float]
    cholesterolPercentDRV: Optional[float]
    copperMg: Optional[float]
    copperPercentRDI: Optional[float]
    fiberG: Optional[float]
    fiberPercentDRV: Optional[float]
    folateMcg: Optional[float]
    folatePercentRDI: Optional[float]
    ironMg: Optional[float]
    ironPercentRDI: Optional[float]
    magnesiumMg: Optional[float]
    magnesiumPercentRDI: Optional[float]
    manganeseMg: Optional[float]
    manganesePercentRDI: Optional[float]
    niacinMg: Optional[float]
    niacinPercentRDI: Optional[float]
    pantothenicAcidMg: Optional[float]
    phosphorusMg: Optional[float]
    phosphorusPercentRDI: Optional[float]
    potassiumMg: Optional[float]
    potassiumPercentRDI: Optional[float]
    proteinG: Optional[float]
    proteinPercentRDI: Optional[float]
    riboflavinMg: Optional[float]
    riboflavinPercentRDI: Optional[float]
    saturatedFatG: Optional[float]
    saturatedFatPercentDRV: Optional[float]
    seleniumMcg: Optional[float]
    seleniumPercentRDI: Optional[float]
    sodiumMg: Optional[float]
    sodiumPercentDRV: Optional[float]
    sugarG: Optional[float]
    sugarPercentDRV: Optional[float]
    thiaminMg: Optional[float]
    thiaminPercentRDI: Optional[float]
    totalFatG: Optional[float]
    totalFatPercentDRV: Optional[float]
    transFatG: Optional[float]
    vitaminAMcg: Optional[float]
    vitaminAPercentRDI: Optional[float]
    vitaminB12Mcg: Optional[float]
    vitaminB12PercentRDI: Optional[float]
    vitaminB6Mg: Optional[float]
    vitaminB6PercentRDI: Optional[float]
    vitaminCMg: Optional[float]
    vitaminCPercentRDI: Optional[float]
    vitaminDMcg: Optional[float]
    vitaminDPercentRDI: Optional[float]
    vitaminEMg: Optional[float]
    vitaminEPercentRDI: Optional[float]
    vitaminKMcg: Optional[float]
    vitaminKPercentRDI: Optional[float]
    zincMg: Optional[float]
    zincPercentRDI: Optional[float]


class UnitFields(BaseModel):
    id: str
    name: str
    unitValues: List["UnitFieldsUnitValues"]


class UnitFieldsUnitValues(BaseModel):
    value: Optional[float]
    unit: "UnitFieldsUnitValuesUnit"


class UnitFieldsUnitValuesUnit(BaseModel):
    id: str
    name: str


CategoryFields.model_rebuild()
NutritionFields.model_rebuild()
UnitFields.model_rebuild()
