# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Optional

from .base_model import BaseModel


class GetOpsRecipeItemConnectionData(BaseModel):
    viewer: "GetOpsRecipeItemConnectionDataViewer"


class GetOpsRecipeItemConnectionDataViewer(BaseModel):
    recipeItemConnection: "GetOpsRecipeItemConnectionDataViewerRecipeItemConnection"


class GetOpsRecipeItemConnectionDataViewerRecipeItemConnection(BaseModel):
    edges: List["GetOpsRecipeItemConnectionDataViewerRecipeItemConnectionEdges"]


class GetOpsRecipeItemConnectionDataViewerRecipeItemConnectionEdges(BaseModel):
    node: "GetOpsRecipeItemConnectionDataViewerRecipeItemConnectionEdgesNode"


class GetOpsRecipeItemConnectionDataViewerRecipeItemConnectionEdgesNode(BaseModel):
    id: str
    recipeId: Optional[str]
    preparations: List[
        "GetOpsRecipeItemConnectionDataViewerRecipeItemConnectionEdgesNodePreparations"
    ]


class GetOpsRecipeItemConnectionDataViewerRecipeItemConnectionEdgesNodePreparations(
    BaseModel
):
    id: str
    name: str
