# Generated by ariadne-codegen
# Source: schema.graphql

from typing import Annotated, Any, List, Optional, Union

from pydantic import Field, PlainSerializer

from .base_model import BaseModel, Upload
